import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const api='/api/v1/ota';
const unwrap=x=>x?.data?.content ?? x?.data ?? x?.content ?? x;
function App(){
 const [config,setConfig]=useState({brand:'AviQR Stays',primary:'#1f7257',accent:'#d5a86b'}),[properties,setProperties]=useState([]),[query,setQuery]=useState(''),[city,setCity]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[rooms,setRooms]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[sort,setSort]=useState('name');
 const [stay,setStay]=useState({checkIn:new Date(Date.now()+86400000).toISOString().slice(0,10),checkOut:new Date(Date.now()+2*86400000).toISOString().slice(0,10),adults:2,children:0});
 useEffect(()=>{fetch(`${api}/config`).then(r=>r.json()).then(setConfig).catch(()=>{});},[]);
 useEffect(()=>{document.documentElement.style.setProperty('--brand',config.primary||'#1f7257');document.documentElement.style.setProperty('--accent',config.accent||'#d5a86b');document.title=`${config.brand||'AviQR Stays'} | Find your stay`;},[config]);
 async function search(e){e?.preventDefault();setLoading(true);setNotice('');try{let all=[];for(let page=0;page<25;page++){const p=new URLSearchParams({q:query,city,page,size:100});const res=await fetch(`${api}/properties?${p}`);if(!res.ok)throw Error();const json=await res.json(),data=json?.data;const rows=Array.isArray(json)?json:(Array.isArray(data)?data:(data?.content||[]));all.push(...rows);if(!data?.totalPages||page+1>=data.totalPages||rows.length===0)break;}const ids=(config.propertyIds||'').split(',').map(x=>x.trim()).filter(Boolean);setProperties(ids.length?all.filter(x=>ids.includes(x.id)):all);}catch{setNotice('We could not load properties. Please try again shortly.');setProperties([]);}finally{setLoading(false);}}
 useEffect(()=>{search();},[config.propertyIds]);
 const shown=useMemo(()=>[...properties].sort((a,b)=>sort==='city'?(a.city||'').localeCompare(b.city||''):(a.name||'').localeCompare(b.name||'')),[properties,sort]);
 async function openProperty(h){setSelected(h);setRooms([]);setNotice('');try{const r=await fetch(`${api}/properties/${h.id}/room-types`);const data=unwrap(await r.json());setRooms(Array.isArray(data)?data:[]);}catch{setNotice('Room options are temporarily unavailable.');}}
 async function book(room,plan,form){setBusy(true);setNotice('');try{const res=await fetch(`${api}/properties/${selected.id}/book`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,checkInDate:stay.checkIn,checkOutDate:stay.checkOut,adults:Number(stay.adults),children:Number(stay.children),roomTypeId:room.roomTypeId,ratePlanId:plan.ratePlanId})});const json=await res.json();if(!res.ok)throw Error(json.message||'Booking could not be completed.');setNotice(`Booking request received. Reference: ${json?.data?.id||json?.data?.reservationId||'see confirmation details'}`);}catch(e){setNotice(e.message||'Booking could not be completed. Please try again.');}finally{setBusy(false);}}
 return <><header className="top"><a className="brand" href="#top">{config.logo?<img src={config.logo} alt=""/>:<span className="brandmark">A</span>}<span>{config.brand||'AviQR Stays'}<small>STAYS, MADE SIMPLE</small></span></a><nav><a href="#stays">Explore stays</a><a href="#how">How it works</a>{config.supportEmail&&<a href={`mailto:${config.supportEmail}`}>Help</a>}</nav><a className="navbutton" href="#stays">Find a stay <span>↗</span></a></header>
 <main id="top"><section className="hero"><div className="hero-copy"><span className="eyebrow">A better kind of getaway</span><h1>Find your place<br/>to <em>slow down.</em></h1><p>Discover welcoming stays across the AviQR collection, with live availability and direct booking.</p></div><div className="hero-art"><div className="sun"/><div className="hill hill-back"/><div className="hill hill-front"/><div className="art-label">Your next stay<br/><b>starts here</b></div></div></section>
 <section className="search-wrap"><form className="search" onSubmit={search}><label className="search-field"><span>DESTINATION</span><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City or anywhere"/></label><label className="search-field"><span>CHECK IN</span><input type="date" value={stay.checkIn} onChange={e=>setStay({...stay,checkIn:e.target.value})}/></label><label className="search-field"><span>CHECK OUT</span><input type="date" value={stay.checkOut} onChange={e=>setStay({...stay,checkOut:e.target.value})}/></label><label className="search-field guests"><span>GUESTS</span><select value={stay.adults} onChange={e=>setStay({...stay,adults:e.target.value})}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} adult{n>1?'s':''}</option>)}</select></label><button className="search-button">Search stays <span>→</span></button></form></section>
 <section className="listing" id="stays"><div className="section-head"><div><span className="eyebrow">THE COLLECTION</span><h2>Somewhere worth going</h2><p>Thoughtful places for the moments you’ll remember.</p></div><label className="sort">Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="city">Destination</option></select></label></div><form className="quick-search" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by property or destination"/><button>Search</button></form>
 {notice&&!selected&&<div className="notice">{notice}</div>}{loading?<div className="empty">Finding lovely places…</div>:shown.length?<div className="grid">{shown.map((h,i)=><article className="card" key={h.id} onClick={()=>openProperty(h)}><div className={`photo photo-${i%4}`}>{h.logoUrl?<img src={h.logoUrl} alt=""/>:<span>{(h.city||h.name||'A').slice(0,1).toUpperCase()}</span>}<i>AV IQR PICK</i></div><div className="card-body"><div className="location">⌖ &nbsp;{h.city||'India'}</div><h3>{h.name}</h3><p>{h.address||'A welcoming place to stay'}</p><div className="card-foot"><span>Explore rooms <b>→</b></span><small>{h.totalRooms?`${h.totalRooms} rooms`:''}</small></div></div></article>)}</div>:<div className="empty"><b>No stays found yet</b><br/>Try another destination or check back soon.</div>}</section>
 <section className="how" id="how"><div><span className="eyebrow">EASY AS IT SHOULD BE</span><h2>From daydream<br/>to checked in.</h2></div><div className="steps"><div><b>01</b><strong>Find your stay</strong><p>Browse AviQR properties and choose where you want to wake up.</p></div><div><b>02</b><strong>Choose your dates</strong><p>See room types and current rates for the nights you need.</p></div><div><b>03</b><strong>Book directly</strong><p>Your reservation goes straight to the property’s PMS.</p></div></div></section></main>
 <footer><a className="brand" href="#top"><span className="brandmark">A</span><span>{config.brand||'AviQR Stays'}<small>STAYS, MADE SIMPLE</small></span></a><span>Good stays begin here.</span><span>© {new Date().getFullYear()} {config.brand||'AviQR'}</span></footer>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-top"><span className="eyebrow">{selected.city||'AVIQR COLLECTION'}</span><h2>{selected.name}</h2><p>{selected.address}</p>{selected.amenities?.length>0&&<div className="amenities">{selected.amenities.slice(0,6).map(a=><span key={a}>{a}</span>)}</div>}</div><div className="modal-body"><h3>Rooms for {stay.checkIn} — {stay.checkOut}</h3>{rooms.length?rooms.map(room=><div className="room" key={room.roomTypeId}><div><b>{room.name}</b><p>{room.description||`Up to ${room.maxOccupancy||2} guests`}</p></div><div className="plans">{room.ratePlans?.map(plan=><PlanChoice key={plan.ratePlanId} hotelId={selected.id} room={room} plan={plan} stay={stay} busy={busy} onBook={form=>book(room,plan,form)}/>)}</div></div>):<div className="empty">Loading available rooms…</div>}{notice&&<div className="notice">{notice}</div>}</div><div className="modal-foot">Rates are quoted by the property PMS. Taxes and payment instructions are confirmed by the property.</div></div></div>}
 </>}
function BookForm({busy,onBook}){const [open,setOpen]=useState(false),[guestName,setName]=useState(''),[guestPhone,setPhone]=useState('');return open?<form className="guest-form" onSubmit={e=>{e.preventDefault();onBook({guestName,guestPhone});}}><input required value={guestName} onChange={e=>setName(e.target.value)} placeholder="Your full name"/><input required value={guestPhone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number"/><button disabled={busy}>{busy?'Booking…':'Confirm booking'}</button></form>:<button className="book-button" onClick={()=>setOpen(true)}>Choose room →</button>}
createRoot(document.getElementById('root')).render(<App/>);

function PlanChoice({hotelId,room,plan,stay,busy,onBook}){const [quote,setQuote]=useState(null),[available,setAvailable]=useState(null);useEffect(()=>{let live=true;const params=new URLSearchParams({roomTypeId:room.roomTypeId,ratePlanId:plan.ratePlanId,checkIn:stay.checkIn,checkOut:stay.checkOut});Promise.all([fetch(`${api}/properties/${hotelId}/quote?${params}`).then(r=>r.ok?r.json():null),fetch(`${api}/properties/${hotelId}/availability?${new URLSearchParams({roomTypeId:room.roomTypeId,checkIn:stay.checkIn,checkOut:stay.checkOut})}`).then(r=>r.ok?r.json():null)]).then(([q,a])=>{if(live){setQuote(q&&unwrap(q));setAvailable(a&&unwrap(a)?.availableRooms);}});return()=>{live=false}},[hotelId,room.roomTypeId,plan.ratePlanId,stay.checkIn,stay.checkOut]);return <div className="plan"><div><b>{plan.name}</b><small>{plan.mealPlan} · {plan.cancellationPolicy||'See property policy'}</small><strong className="price">{quote?.totalBeforeTax!=null?`${quote.currency||'INR'} ${Number(quote.totalBeforeTax).toLocaleString('en-IN')} · before tax`:`${plan.baseRate?`From INR ${Number(plan.baseRate).toLocaleString('en-IN')} / night`:'Price on request'}`}</strong><small>{available===null?'Checking availability…':available>0?`${available} room${available===1?'':'s'} available`:'Sold out for these dates'}</small></div>{available>0?<BookForm busy={busy} onBook={onBook}/>:<button className="book-button" disabled>{available===0?'Unavailable':'Checking…'}</button>}</div>}
